# **Lab: Engineering for ML**

## Exercise 1: EDA and Baseline Model

In this exercise we will start our data science project by preparing the dataset for modeling

**Pre-requisites:**
- Create a github account (https://github.com/join)
- Install git (https://git-scm.com/book/en/v2/Getting-Started-Installing-Git)
- Install uv (https://docs.astral.sh/uv/getting-started/installation/)
- Install Wget for Windows users (https://eternallybored.org/misc/wget/)

The steps are:
1.   Setup Environment
2.   Load and explore dataset
3.   Prepare Data
4.   Split Dataset
5.   Get Baseline model
6.   Push changes

## 1. Setup Environment

**[1.1]** You should already have an active Jupyter Lab session and the dataset uploaded into the relevant folder

**[1.2]** Create a new Jupyter Notebook called `1_baseline.ipynb` inside the `work/adv_mla_lab_1/notebooks/` directory


## 2. Load and Explore Dataset

**[2.1]** Launch magic commands to automatically reload modules

In [25]:
%load_ext autoreload
%autoreload 2

**[2.2]** Import the pandas and numpy package

In [26]:
import pandas as pd
import numpy as np

**[2.3]** Load the dataset into dataframe called df

In [27]:
df= pd.read_csv('C:/Users/manus/projects/adv_mla_2026/adv_mla_lab_1/data/raw/wfh.csv')

**[2.4]** Display the first 5 rows of df

In [28]:
df.head()

,id,distance_from_office,salary_range,gas_price_per_litre,public_transportation_cost,wfh_prev_workday,workday,tenure,work_home_actual
0,0,5.962247,40K - 60K,2.119485,8.568058,False,Friday,0.212653,1
1,1,0.535872,40K - 60K,2.357199,5.425382,True,Tuesday,4.927549,0
2,2,1.969519,40K - 60K,2.366849,8.247158,False,Monday,0.520817,1
3,3,2.530410,20K - 40K,2.318722,7.944251,False,Tuesday,0.453649,1
4,4,2.253635,60K+,2.221265,8.884478,True,Thursday,5.695263,1

**[2.5]** Display the dimensions (shape) of df

In [29]:
df.shape

(50000, 9)

**[2.6]** Display the summary (info) of df

In [30]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   id                          50000 non-null  int64
 1   distance_from_office        50000 non-null  float64
 2   salary_range                50000 non-null  str
 3   gas_price_per_litre         50000 non-null  float64
 4   public_transportation_cost  50000 non-null  float64
 5   wfh_prev_workday            50000 non-null  bool
 6   workday                     50000 non-null  str
 7   tenure                      50000 non-null  float64
 8   work_home_actual            50000 non-null  int64
dtypes: bool(1), float64(4), int64(2), str(2)
memory usage: 3.1 MB

**[2.7]** Display the descriptive statistics of df

In [31]:
df.describe(include='all')

,id,distance_from_office,salary_range,gas_price_per_litre,public_transportation_cost,wfh_prev_workday,workday,tenure,work_home_actual
count,50000.000000,50000.000000,50000,50000.000000,50000.000000,50000,50000,50000.000000,50000.000000
unique,NaN,NaN,4,NaN,NaN,2,5,NaN,NaN
top,NaN,NaN,0 - 20K,NaN,NaN,True,Wednesday,NaN,NaN
freq,NaN,NaN,19918,NaN,NaN,27547,10095,NaN,NaN
mean,24999.500000,3.929033,NaN,2.049616,7.323907,NaN,NaN,4.600040,0.499580
std,14433.901067,4.079528,NaN,0.334385,1.630390,NaN,NaN,2.301937,0.500005
min,0.000000,0.002210,NaN,1.400369,4.003417,NaN,NaN,0.002253,0.000000
25%,12499.750000,0.897909,NaN,1.769163,6.109763,NaN,NaN,2.797947,0.000000
50%,24999.500000,2.380855,NaN,2.189073,8.074422,NaN,NaN,5.584845,0.000000
75%,37499.250000,5.679015,NaN,2.337894,8.627489,NaN,NaN,6.531917,1.000000
max,49999.000000,19.912896,NaN,2.399916,8.998112,NaN,NaN,6.997167,1.000000

## 3. Prepare Data

**[3.1]** Create a copy of df and save it into a variable called df_cleaned

In [32]:
df_cleaned=df.copy()

**[3.2]** Extract the column `work_home_actual` and save it into variable called `y`

In [33]:
y=df_cleaned.pop('work_home_actual')

**[3.3]** Import OrdinalEncoder from sklearn.preprocessing

In [35]:
from sklearn.preprocessing import OrdinalEncoder

**[3.4]** Instantiate a OrdinalEncoder with the values from `workday` column

In [42]:
ord_enc = OrdinalEncoder(categories=[['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']])

**[3.5]** Fit and apply the OrdinalEncoder on `workday` column and replace with the encoded values

In [43]:
df_cleaned['workday'] = ord_enc.fit_transform(df_cleaned[['workday']])

In [44]:
df_cleaned

,id,distance_from_office,salary_range,gas_price_per_litre,public_transportation_cost,wfh_prev_workday,workday,tenure
0,0,5.962247,40K - 60K,2.119485,8.568058,False,4.0,0.212653
1,1,0.535872,40K - 60K,2.357199,5.425382,True,1.0,4.927549
2,2,1.969519,40K - 60K,2.366849,8.247158,False,0.0,0.520817
3,3,2.530410,20K - 40K,2.318722,7.944251,False,1.0,0.453649
4,4,2.253635,60K+,2.221265,8.884478,True,3.0,5.695263
...,...,...,...,...,...,...,...,...
49995,49995,2.356053,20K - 40K,2.344472,8.763312,False,4.0,3.960767
49996,49996,4.897964,0 - 20K,1.601283,8.795181,False,3.0,6.804872
49997,49997,0.869910,40K - 60K,2.262292,8.360564,True,2.0,5.101474
49998,49998,10.336794,0 - 20K,1.516446,8.733694,False,4.0,6.738282
49999,49999,2.815616,20K - 40K,2.244124,7.473265,True,2.0,6.741473

**[3.6]** Apply OneHotEncoding on `salary_range` and save the result back in `df_cleaned`

In [45]:
df_cleaned = pd.get_dummies(df_cleaned, columns=['salary_range'])

**[3.7]** Remove the `id` column from `df_cleaned`

In [46]:
df_cleaned.drop(["id"], axis=1, inplace=True)

## 4. Split Dataset

**[4.1]** import train_test_split from sklearn.model_selection

In [47]:
from sklearn.model_selection import train_test_split

**[4.2]** Split the data into training validation and testing sets as Numpy arrays

In [48]:
x_data, X_test, y_data, y_test = train_test_split(df_cleaned, y, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(x_data, y_data, test_size=0.2, random_state=42)

**[4.3]** Print the dimensions of `X_train`, `X_val`, `X_test`

In [50]:
print(X_train.shape)
print(X_val.shape)
print(X_test.shape)

(32000, 10)
(8000, 10)
(10000, 10)

**[4.4]** Print the dimensions of `y_train`, `y_val`, `y_test`

In [51]:
print(y_train.shape)
print(y_val.shape)
print(y_test.shape)

(32000,)
(8000,)
(10000,)

**[4.5]** Save the sets into the folder `data/processed`

In [52]:
X_train.to_csv('C:/Users/manus/projects/adv_mla_2026/adv_mla_lab_1/data/processed/X_train.csv', index=False)
X_val.to_csv('C:/Users/manus/projects/adv_mla_2026/adv_mla_lab_1/data/processed/X_val.csv', index=False)
X_test.to_csv('C:/Users/manus/projects/adv_mla_2026/adv_mla_lab_1/data/processed/X_test.csv', index=False)
y_train.to_csv('C:/Users/manus/projects/adv_mla_2026/adv_mla_lab_1/data/processed/y_train.csv', index=False)
y_val.to_csv('C:/Users/manus/projects/adv_mla_2026/adv_mla_lab_1/data/processed/y_val.csv', index=False)
y_test.to_csv('C:/Users/manus/projects/adv_mla_2026/adv_mla_lab_1/data/processed/y_test.csv', index=False)

## 5. Get Baseline Model

**[5.1]** Import the DummyClassifier module from sklearn

In [53]:
from sklearn.dummy import DummyClassifier

**[5.2]** Instantiate the Dummy class into a variable called `base_clf` and fit it on the training set it

In [55]:
base_clf = DummyClassifier(strategy='most_frequent', random_state=42)
base_clf.fit(X_train, y_train)

DummyClassifier(random_state=42, strategy='most_frequent')

**[5.3]** Import roc_auc_score from sklearn.metrics

In [56]:
from sklearn.metrics import roc_auc_score

**[5.6]** Display the ROC scores of this baseline model on the training set

In [59]:
y_proba_preds = base_clf.predict_proba(X_train)
roc_auc_score(y_train, y_proba_preds[:, 1])

0.5

In [58]:
y_proba_preds

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], shape=(32000, 2))

## 6.   Push changes

**[6.1]** Add your changes to git staging area

In [ ]:
# Placeholder for student's code (command line)

In [ ]:
# Solution:
! git add .

**[6.2]** Create the snapshot of your repository and add a description

In [ ]:
# Placeholder for student's code (command line)

In [ ]:
# Solution:
! git commit -m "prepare data and baseline"

[main 8956cb2] prepare data and baseline
 Committer: Anthony So <anthonyso@Mac.gateway>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly:

    git config --global user.name "Your Name"
    git config --global user.email you@example.com

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 1 file changed, 978 insertions(+)
 create mode 100644 notebooks/1-baseline.ipynb

**[6.3]** Push your snapshot to Github

In [ ]:
# Placeholder for student's code (command line)

In [ ]:
# Solution:
! git push

Enumerating objects: 6, done.
Counting objects: 100% (6/6), done.
Delta compression using up to 10 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 3.76 KiB | 3.76 MiB/s, done.
Total 4 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To github.com-uts:aso-uts/adv_mla_lab_1.git
   58ed004..8956cb2  main -> main